reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
  request_changes_workflow: true
  path_filters:
    - "**/*"
    - "!**/*.md"
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/_generated/**"

language: "en-US"
